name: Deploy MkDocs to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main 
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mkdocs

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
